Bug Fixed-1. Last Beta Commit

diff --git a/bin/Webscraping-based_Creatify/creatify b/bin/Webscraping-based_Creatify/creatify
--- a/bin/Webscraping-based_Creatify/creatify
+++ b/bin/Webscraping-based_Creatify/creatify
@@ -19,7 +19,7 @@ path_file="$main_dir/paths.sh"
 data_file="$main_dir/github.pyc"
 config_file="$main_dir/configure.sh"
 def_py_file="$main_dir/create.py"
-gitignore_file="$main_dir/.gitignore"
+gitignore_file="$main_dir/gitignoreTexts.txt"
 webtemplate_file="$main_dir/webtemplate.sh"
 
 [[ -e "$path_file" ]] && : || `bash "$config_file" "pathFile"`
@@ -33,7 +33,8 @@ languages=( "python" "flutter" "web" "node" "default" )
 
 if [[ $1 == "--config" ]]
 then
-    # python3 "$config_file" "config"
+    [[ -e "$config_file" ]] && : || (echo "Your Config File is Missing.. So You Can Not Change Settings Anymore.."; exit 1)
+    bash "$config_file" "$2"
     exit
 fi
 
@@ -92,8 +93,7 @@ function webTemplate(){
 function createProject(){
     path="$1"
     name="$2"
-    editor="$3"
-    lang=$4
+    lang="$3"
     if cd "$path"
     then
         if [[ $lang == "flutter" ]]
@@ -110,11 +110,12 @@ function createProject(){
             
             if [[ $pname == "" ]]
             then
-                flutter create $title > /dev/null 2>&1
+                flutter create $title 
             else
-                flutter create --org $pname $title > /dev/null 2>&1
+                flutter create --org $pname $title 
             fi
             cd "./$title"
+            git init
             python3 "$def_py_file" "$title"
             touch "README.md"
             git add .
@@ -211,7 +212,7 @@ fi
 . "$path_file"
 eval "path=\$$lang"
 
-if [[ $path="" ]]
+if [[ $path == "" ]]
 then
     echo "Path for $lang projects was not given while configuring Creatify."
     echo "run \"creatify --config path\" to configure paths again.."
